apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-iac-skeleton-pro

images:
  - name: alpine
    newName: alpine
    newTag: 3.20.1

labels:
  - pairs:
      app.acampos.local/env: PRO
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../base
  - resources/pod-disruption-budget.yaml

components:
  - git@github.com:angelcamposm/krm-taints-and-tolerations-component.git
  - git@github.com:angelcamposm/krm-pod-topology-spread-component.git
  - git@github.com:angelcamposm/krm-node-affinity-component.git