apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-iac-skeleton-pro

images:
  - name: alpine
    newName: alpine
    newTag: 3.20.1

labels:
  - pairs:
      app.acampos.local/env: PRO
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../base

