apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-iac-skeleton-dev

images:
  - name: alpine
    newName: alpine
    newTag: 3.20.1

labels:
  - pairs:
      app.acampos.local/env: DEV
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../base

patches:
  - path: patches/add-storage-volume-patch.yaml
    target:
      group: apps
      kind: Deployment
      version: v1
