apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-awesome-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-awesome-application
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
