apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-iac-skeleton

labels:
  - pairs:
      app.acampos.local/name: my-awesome-application
    includeSelectors: true
    includeTemplates: true
